stages:
  build_features:
    cmd: python .\src\features\build_features.py 
      .\data\processed\Cleaned_car_dataset.csv
    deps:
    - .\data\processed\Cleaned_car_dataset.csv
    - .\src\features\build_features.py
    outs:
    - .\data\processed\cleaned_car_v1.csv

  impute_model:
    cmd: python .\src\train_inpute_model\impute_model.py 
      .\data\processed\cleaned_car_v1.csv
    deps:
    - .\data\processed\cleaned_car_v1.csv
    - .\src\train_inpute_model\impute_model.py
    outs:
    - .\data\processed\cleaned_car_v2.csv

  export_dataset_file:
    cmd: python .\src\data\export_dataset_file.py 
      .\data\processed\cleaned_car_v2.csv
    deps:
    - .\data\processed\cleaned_car_v2.csv
    - .\src\data\export_dataset_file.py
    outs:
    - .\models\dataset.joblib

  make_dataset:
    cmd: python .\src\data\make_dataset.py .\models\dataset.joblib
    deps:
    - .\models\dataset.joblib
    - .\src\data\make_dataset.py
    params:
    - make_dataset.test_split
    - make_dataset.seed
    outs:
    - .\data\processed\train.csv
    - .\data\processed\test.csv

  train_model:
    cmd: python .\src\models\train_model.py .\data\processed\train.csv
    deps:
    - .\data\processed\train.csv
    - .\src\models\train_model.py
    params:
    - train_model.learning_rate
    - train_model.max_depth
    - train_model.min_samples_leaf
    - train_model.min_samples_split
    - train_model.n_estimators
    outs:
    - .\models\model.joblib

  predict_model:
    cmd: python .\src\models\predict_model.py .\models\model.joblib 
      .\data\processed\train.csv
    deps:
    - .\data\processed\train.csv
    - .\models\model.joblib
    - .\src\models\predict_model.py
    outs:
    - .\models\pipeline.joblib
    - .\pipeline.joblib

  visualize:
    cmd: python .\src\visualization\visualize.py .\models\pipeline.joblib 
      .\data\processed\
    deps:
    - .\data\processed\
    - .\models\pipeline.joblib
    - .\src\visualization\visualize.py
